# Copyright 2017, Backblaze Inc. All Rights Reserved.
# License https://www.backblaze.com/using_b2_code.html

# travis-ci is about to change the default to 'trusty', so let's
# switch to it on purpose.  we can probably remove in August 2017.
# see https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming
dist: trusty

language: java

jdk:
  - oraclejdk8

env:
  - OUTPUT_ZIP=b2sdk4j-build-${TRAVIS_BUILD_NUMBER}.zip

before_install:
  - mkdir -p ~/.gradle && echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
  - sudo pip install b2

script:
  #
  # actually build
  #

  - ./gradlew build javadoc

  #
  # Prepare the outputs
  #

  # make the directory
  - mkdir -p build/outputs
  
  # copy the generated jar files
  - cp -v */build/libs/b2sdk4j-*.jar build/outputs

  # make the 'sources' zip
  - zip -r build/outputs/b2sdk4j-core-sources.zip core/src
  - zip -r build/outputs/b2sdk4j-httpclient-sources.zip httpclient/src
  - zip -r build/outputs/b2sdk4j-samples-sources.zip samples/src

  # make the javadocs zip
  - (cd core/build/docs; zip -r $TRAVIS_BUILD_DIR/build/outputs/b2sdk4j-core-javadocs.zip javadoc)
  - (cd httpclient/build/docs; zip -r $TRAVIS_BUILD_DIR/build/outputs/b2sdk4j-httpclient-javadocs.zip javadoc)

  # zip up the outputs
  - echo OUTPUT_ZIP=$OUTPUT_ZIP
  - (cd build/outputs; zip $TRAVIS_BUILD_DIR/build/$OUTPUT_ZIP *)

  #
  # upload to b2
  #

  - b2 authorize_account $B2_ACCOUNT_ID $B2_APPLICATION_KEY
  - b2 upload_file --contentType application/octet b2sdk4j build/$OUTPUT_ZIP builds/$OUTPUT_ZIP

  # list all files to help debug stuff!
  - find $TRAVIS_BUILD_DIR

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

# note that i'm only uploading the javadocs for b2sdk4j-core.
# that's because i'm lame and building separate javadocs for
# each jar and only uploading one set of javadocs.
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: core/build/docs/javadoc
  on:
    branch: master
